<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <RootNamespace>Bem.ReactiveUI.Blazor.Extras</RootNamespace>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-all</AnalysisLevel> 
    <Nullable>enable</Nullable>
	  <LangVersion>12.0</LangVersion>
	<ImplicitUsings>enable</ImplicitUsings>
    <Authors>Daniel Balogh</Authors>
    <Configurations>Debug;Release</Configurations>
    <IncludeSymbols>True</IncludeSymbols>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
	<PropertyGroup>
		<NoWarn>CA1510;CA1513</NoWarn>
	</PropertyGroup>
  <PropertyGroup>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <Authors>Daniel Balogh</Authors>
    <GITHUB_SERVER_URL>https://github.com</GITHUB_SERVER_URL>
    <GITHUB_REPOSITORY>bemobolo/Bem.ReactiveUI.Blazor.Extras</GITHUB_REPOSITORY>
    <Description>An extension for ReactiveUI.Blazor to optimize change tracking of complex view models and make rendering more performant.</Description>
    <PackageProjectUrl>$(GITHUB_SERVER_URL)/$(GITHUB_REPOSITORY)</PackageProjectUrl>
    <RepositoryUrl>$(GITHUB_SERVER_URL)/$(GITHUB_REPOSITORY)</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>mvvm;reactiveui;rx;reactive extensions;observable;blazor;web;</PackageTags>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>
	<ItemGroup>
		<None Include="icon.png" Pack="true" PackagePath="" />
	</ItemGroup>
  <ItemGroup Condition=" $(TargetFramework.StartsWith('net8')) ">
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="8.*" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('net9')) ">
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.*" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('net10')) ">
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
    <PackageReference Include="DynamicData" Version="9.4.33" />
    <PackageReference Include="ReactiveUI.Blazor" Version="25.1.1" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bem.ReactiveUI.Blazor.Extras.CodeGenerators\Bem.ReactiveUI.Blazor.Extras.CodeGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.401">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="IDisposableAnalyzers" Version="4.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Analyzers" Version="5.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.35.0.4138">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>